#===============================================================================
                        Compute interesting values
===============================================================================#
export BaseOutput, TrajectoryOutput, CustomOutput

const EOL="\n"
const TAB="\t"

abstract BaseOutput

type TrajectoryOutput <: BaseOutput
    writer::Writer
end

function write(out::TrajectoryOutput, context::Dict)
    write(out.writer, context[:frame])
end

# Write to a file, each line containing the results of
# string interpolation on CustomOutput.values
type CustomOutput <: BaseOutput
    file::IOStream
    values::Vector{Symbol}
end

function CustomOutput(filename::String, values::Vector{Symbol},
                            header::String="# Generated by Jumos package")

    file = open(filename, "w")
    write(file, header * EOL)
    return CustomOutput(file, values, header)
end

function write(out::CustomOutput, context::Dict)
    s = ""
    for value in out.values
        try
            s *= TAB * context[value]
        catch KeyError
            error("Value not found in output: $(KeyError.key)")
        end
    end
    write(out.file, s * EOL)
end
