# -*- coding: utf-8 -*-
#
# Jumos documentation build configuration file, created by
# sphinx-quickstart on Fri Oct 31 13:07:55 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import sphinx_rtd_theme

DOC_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(DOC_DIR, "_ext_"))
import juliadoc

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'juliadoc.julia'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates_']

# The suffix of source filenames.
source_suffix = '.rst'

# This will be included at the end of all the files.
rst_epilog = """
.. |Jumos| replace:: *Jumos*
"""

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Jumos'
copyright = u'2014-2015, Guillaume Fraux -- CC-BY-SA licence'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.2'
# The full version, including alpha/beta/rc tags.
release = version

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['__build__',]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static_']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
html_extra_path = ["_static_/img/logo.png"]

# -- Options for LaTeX output ---------------------------------------------

with open(os.path.join("_templates_", "preamble.tex")) as f:
    preamble = f.read()

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
'preamble': preamble,
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'Jumos.tex', u'Main Documentation',
   u'Guillaume Fraux', 'howto'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = os.path.join('_static_', 'img', 'logo.pdf')

# If true, show page references after internal links.
latex_show_pagerefs = True
